import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";

import localFont from "next/font/local";

const ottoAttackType = localFont({
   src: "./fonts/OTTOATTACTYPE.ttf",
  variable: "--font-otto-attack",
  weight: "400", // Вкажіть відповідну вагу
});

const montserrat = Montserrat({
  weight: ["400", "700"], // Додаємо потрібні варіанти товщини шрифту
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${montserrat.variable} antialiased`}>
      <Header />
        {children}
      </body>
    </html>
  );
}
